### ISSUE TITLE
API - Create new tenant 

### ISSUE THREAD

**Issue by moshloop** [flanksource/tenant-controller#1]
Write a REST API using some of the code in the git-operator:

1. On a POST to `/tenant` with:
```yaml
name: Acme Corp
slug: acme-corp
cloud: aws|azure| # Which cloud to provision the tenant in
```
2. Generate a user/pass 
3. Sops encrypt the db secret with the relevant cloud provider credentials 
4. Create the yaml manifest and update kustomization.yaml to insert a new tenant
5. Create a PR to the relevant directory: https://github.com/flanksource/aws-sandbox/tree/main/azure-internal-prod/spec/environments/production/tenants

wdyt @Kaitou786 @yashmehrotra
